# Generated by Django 2.1.11 on 2019-10-20 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('paste', models.TextField()),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('c', 'public'), ('p', 'private')], default='c', max_length=1)),
                ('Expireation', models.CharField(choices=[('Never', 'never'), ('10m', '10 minute'), ('1h', '1hour'), ('1day', 'One Day'), ('1week', 'One Week'), ('2weeks', 'Two Weeks'), ('1month', 'One Month')], default='never', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyntaxHighLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pastes',
            name='syntax_highlight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syntax', to='pastes.SyntaxHighLight'),
        ),
        migrations.AddField(
            model_name='pastes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastes', to=settings.AUTH_USER_MODEL),
        ),
    ]
