# Generated by Django 2.1.11 on 2019-10-20 20:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pastes',
            new_name='Paste',
        ),
    ]
