# Generated by Django 2.1.11 on 2019-10-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0002_auto_20191020_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
