# Generated by Django 2.1.11 on 2019-10-20 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0003_auto_20191020_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastes', to=settings.AUTH_USER_MODEL),
        ),
    ]
